modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/YukkuriC/CreateCollectionBundles/issues"
license = "MIT"

[[mods]]
modId = "create_collection_bundles"
version = "${version}"
displayName = "Create: Collection Bundles"
authors = "YukkuriC"
description = '''
Adds feature for Create logistic system to extract items from several types of blocks
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/dRqIMksA/forge_updates.json"
displayURL = "https://modrinth.com/mod/create-collection-bundles"

[[dependencies.create_collection_bundles]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_collection_bundles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.1.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_collection_bundles]]
modId = "create"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_collection_bundles]]
modId = "refinedstorage"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
